//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stencil.Data.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbAsset
    {
        public System.Guid asset_id { get; set; }
        public int type { get; set; }
        public bool available { get; set; }
        public bool resize_required { get; set; }
        public bool encode_required { get; set; }
        public bool resize_processing { get; set; }
        public bool encode_processing { get; set; }
        public string thumb_small_dimensions { get; set; }
        public string thumb_medium_dimensions { get; set; }
        public string thumb_large_dimensions { get; set; }
        public string resize_status { get; set; }
        public int resize_attempts { get; set; }
        public Nullable<System.DateTimeOffset> resize_attempt_utc { get; set; }
        public string encode_identifier { get; set; }
        public string encode_status { get; set; }
        public string raw_url { get; set; }
        public string public_url { get; set; }
        public string thumb_small_url { get; set; }
        public string thumb_medium_url { get; set; }
        public string thumb_large_url { get; set; }
        public string encode_log { get; set; }
        public string resize_log { get; set; }
        public int dependencies { get; set; }
        public int encode_attempts { get; set; }
        public Nullable<System.DateTimeOffset> encode_attempt_utc { get; set; }
        public string resize_mode { get; set; }
        public System.DateTimeOffset created_utc { get; set; }
        public System.DateTimeOffset updated_utc { get; set; }
    }
}
