/*!
* StencilSDKDuo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
*
* Generated by DuoCode Compiler 2.2.1631.0 [Professional]
*/
(function StencilSDKDuo() {
"use strict";
var $asm = {
    fullName: "StencilSDKDuo",
    anonymousTypes: [],
    types: [],
    getAttrs: function() { return [new System.Reflection.AssemblyTitleAttribute.ctor("Stencil.SDK.Web"), new System.Reflection.AssemblyDescriptionAttribute.ctor(""), new System.Reflection.AssemblyConfigurationAttribute.ctor(""), new System.Reflection.AssemblyCompanyAttribute.ctor(""), new System.Reflection.AssemblyProductAttribute.ctor("Stencil.SDK.Web"), new System.Reflection.AssemblyCopyrightAttribute.ctor("Copyright \xA9  2016"), new System.Reflection.AssemblyTrademarkAttribute.ctor(""), new System.Reflection.AssemblyCultureAttribute.ctor(""), new System.Reflection.AssemblyVersionAttribute.ctor("1.0.0.0"), new System.Reflection.AssemblyFileVersionAttribute.ctor("1.0.0.0"), new DuoCode.Runtime.CompilerAttribute.ctor("2.2.1631.0")]; }
};
var $g = (typeof(global) !== "undefined" ? global : (typeof(window) !== "undefined" ? window : self));
var Stencil = $g.Stencil = $g.Stencil || {};
var System = $g.System = $g.System || {};
System.Security = System.Security || {};
System.Security.Cryptography = System.Security.Cryptography || {};
var RestSharp = $g.RestSharp = $g.RestSharp || {};
Stencil.SDK = Stencil.SDK || {};
Stencil.SDK.Security = Stencil.SDK.Security || {};
Stencil.SDK.Endpoints = Stencil.SDK.Endpoints || {};
Stencil.SDK.Models = Stencil.SDK.Models || {};
Stencil.SDK.Models.Requests = Stencil.SDK.Models.Requests || {};
Stencil.SDK.Models.Responses = Stencil.SDK.Models.Responses || {};
var $d = DuoCode.Runtime;
$d.$assemblies["StencilSDKDuo"] = $asm;
Stencil.Client = $d.declare("Stencil.Client", 0, $asm);
System.Security.Cryptography.MD5 = $d.declare("System.Security.Cryptography.MD5", 0, $asm);
RestSharp.RestRequest = $d.declare("RestSharp.RestRequest", 0, $asm);
Stencil.SDK.Security.HashedTimeSignatureGenerator = $d.declare("Stencil.SDK.Security.HashedTimeSignatureGenerator", 
    0, $asm);
Stencil.SDK.StencilSDK = $d.declare("Stencil.SDK.StencilSDK", 0, $asm);
Stencil.WebAssumptions = $d.declare("Stencil.WebAssumptions", 0, $asm);
Stencil.SDK.ActionResult = $d.declare("Stencil.SDK.ActionResult", 0, $asm);
Stencil.SDK.Endpoints.AuthEndpoint = $d.declare("Stencil.SDK.Endpoints.AuthEndpoint", 0, $asm);
Stencil.SDK.Endpoints.AccountEndpoint = $d.declare("Stencil.SDK.Endpoints.AccountEndpoint", 0, $asm);
Stencil.SDK.Endpoints.AssetEndpoint = $d.declare("Stencil.SDK.Endpoints.AssetEndpoint", 0, $asm);
Stencil.SDK.Endpoints.GlobalSettingEndpoint = $d.declare("Stencil.SDK.Endpoints.GlobalSettingEndpoint", 
    0, $asm);
Stencil.SDK.Endpoints.EndpointBase = $d.declare("Stencil.SDK.Endpoints.EndpointBase", 0, $asm);
Stencil.SDK.IDPair = $d.declare("Stencil.SDK.IDPair", 0, $asm);
Stencil.SDK.ItemResult$1 = $d.declare("Stencil.SDK.ItemResult`1", 256, $asm);
Stencil.SDK.ItemResult$2 = $d.declare("Stencil.SDK.ItemResult`2", 256, $asm);
Stencil.SDK.ListResult$1 = $d.declare("Stencil.SDK.ListResult`1", 256, $asm);
Stencil.SDK.ListResult$2 = $d.declare("Stencil.SDK.ListResult`2", 768, $asm);
Stencil.SDK.Models.Asset = $d.declare("Stencil.SDK.Models.Asset", 0, $asm);
Stencil.SDK.Models.Requests.AuthLoginInput = $d.declare("Stencil.SDK.Models.Requests.AuthLoginInput", 
    0, $asm);
Stencil.SDK.Models.Requests.PasswordResetInput = $d.declare("Stencil.SDK.Models.Requests.PasswordResetInput", 
    0, $asm);
Stencil.SDK.Models.Requests.RegisterInput = $d.declare("Stencil.SDK.Models.Requests.RegisterInput", 0, 
    $asm);
Stencil.SDK.Models.Responses.AccountInfo = $d.declare("Stencil.SDK.Models.Responses.AccountInfo", 0, 
    $asm);
Stencil.SDK.Models.SDKModel = $d.declare("Stencil.SDK.Models.SDKModel", 0, $asm);
Stencil.SDK.PagingInfo = $d.declare("Stencil.SDK.PagingInfo", 0, $asm);
Stencil.SDK.StencilAuthInfo = $d.declare("Stencil.SDK.StencilAuthInfo", 0, $asm);
Stencil.SDK.Models.Account = $d.declare("Stencil.SDK.Models.Account", 0, $asm);
Stencil.SDK.Models.GlobalSetting = $d.declare("Stencil.SDK.Models.GlobalSetting", 0, $asm);
Stencil.SDK.SteppingInfo = $d.declare("Stencil.SDK.SteppingInfo", 0, $asm);
Stencil.SDK._ResultExtensions = $d.declare("Stencil.SDK._ResultExtensions", 0, $asm);
$d.define(Stencil.Client, null, function($t, $p) {
    $t.Create = function Client_Create(baseUrl) {
        return new Stencil.SDK.StencilSDK.ctor$1(baseUrl);
    };
});
$d.define(System.Security.Cryptography.MD5, null, function($t, $p) {
    $t.ctor = function MD5() {
        $t.$baseType.ctor.call(this);
    };
    $t.Create = function MD5_Create() {
        return new System.Security.Cryptography.MD5.ctor();
    };
    $p.GenerateHash = function MD5_GenerateHash(content) {
        var sdkBridge = StencilSDKBridge;
        return sdkBridge.generateMD5Hash(content);
    };
});
RestSharp.Method = $d.typeEnum("RestSharp.Method", 45, $asm, 257, ["GET", "POST", "PUT", "DELETE"], [0, 1, 2, 3]);
$d.define(RestSharp.RestRequest, null, function($t, $p) {
    $t.$ator = function() {
        this.Method = 0 /* Method */;
        this.Resource = null;
        this.JsonBody = null;
        this.Parameters = null;
        this.Segments = null;
        this.ContentType = null;
    };
    $t.ctor = function RestRequest(method) {
        $t.$baseType.ctor.call(this);
        this.Method = method;
        this.Parameters = new (System.Collections.Generic.Dictionary$2(String, System.Object, 58817).ctor)();
        this.Segments = new (System.Collections.Generic.Dictionary$2(String, String, 27758).ctor)();
        this.ContentType = "application/json";
    };
    $p.AddJsonBody = function RestRequest_AddJsonBody(body) {
        this.JsonBody = body;
    };
    $p.AddParameter = function RestRequest_AddParameter(name, value) {
        this.Parameters.set_Item(name, value);
    };
    $p.AddFile = function RestRequest_AddFile(name, value, fileName) {
        this.ContentType = "multipart/form-data";
        this.Parameters.set_Item(name, value);
    };
    $p.AddUrlSegment = function RestRequest_AddUrlSegment(name, value) {
        this.Segments.set_Item(name, value);
    };
    $p.GetResource = function RestRequest_GetResource() {
        var result = this.Resource;
        var $iter = this.Segments;
        var $enumerator = $iter.System$Collections$IEnumerable$GetEnumerator();
        while ($enumerator.System$Collections$IEnumerator$MoveNext()) {
            var item = $enumerator.System$Collections$IEnumerator$get_Current();
            result = result.Replace$1("{" + item.get_Key() + "}", item.get_Value());
        }
        return result;
    };
    $p.GetData = function RestRequest_GetData() {
        if (this.JsonBody != null) {
            return this.JsonBody;
        }
        return this.Parameters;
    };
});
$d.define(Stencil.SDK.Security.HashedTimeSignatureGenerator, null, function($t, $p) {
    $t.ctor = function HashedTimeSignatureGenerator() {
        $t.$baseType.ctor.call(this);
    };
    $p.GetUnixTime = function HashedTimeSignatureGenerator_GetUnixTime() {
        var sdkBridge = StencilSDKBridge;
        return sdkBridge.getTimeStamp();
    };
    $p.CreateSignature = function HashedTimeSignatureGenerator_CreateSignature(apiKey, apiSecret) {
        var prefix = String.Format("{0}{1}", $d.array(System.Object, [apiKey, apiSecret]));
        var unixUTCNow = this.GetUnixTime().toString();
        return System.Security.Cryptography.MD5.Create().GenerateHash(prefix + unixUTCNow);

    };
});
$d.define(Stencil.SDK.StencilSDK, null, function($t, $p) {
    $t.cctor = function() {
        $t.API_BASE_URL = "https://stencil.socialhaven.com/api";
        $t.API_PARAM_KEY = "api_key";
        $t.API_PARAM_SIG = "api_signature";
    };
    $t.$ator = function() {
        this.Auth = null;
        this.AsyncTimeoutMillisecond = 0;
        this.BaseUrl = null;
        this.ApplicationKey = null;
        this.ApplicationSecret = null;
        this.GlobalSetting = null;
        this.Account = null;
        this.Asset = null;
        this.CustomHeaders = null;
        this.SignatureGenerator = null;
        this.InstanceCache = null;
    };
    $p.ExecuteAsync = function StencilSDK_ExecuteAsync(T, request) {
        var sdkBridge = StencilSDKBridge;
        var jsonBody = null;
        var headers = new (System.Collections.Generic.List$1(System.Collections.Generic.KeyValuePair$2(String, 
            String, 27758), 13064).ctor)();
        var parameters = null;

        // body
        if (request.JsonBody != null) {
            jsonBody = request.GetData();
        }

        //parameters
        if (request.Parameters.get_Values().System$Collections$Generic$ICollection$1$get_Count() > 0) {
            parameters = new (System.Collections.Generic.List$1(System.Collections.Generic.KeyValuePair$2(String, 
                System.Object, 58817), 11647).ctor)();
            var $iter = request.Parameters;
            var $enumerator = $iter.System$Collections$IEnumerable$GetEnumerator();
            while ($enumerator.System$Collections$IEnumerator$MoveNext()) {
                var item = $enumerator.System$Collections$IEnumerator$get_Current();
                parameters.Add(item);
            }
        }

        // custom headers
        if (this.get_CustomHeaders() != null) {
            var $iter1 = this.get_CustomHeaders();
            var $enumerator1 = $iter1.System$Collections$IEnumerable$GetEnumerator();
            while ($enumerator1.System$Collections$IEnumerator$MoveNext()) {
                var item = $enumerator1.System$Collections$IEnumerator$get_Current();
                headers.Add(item);
            }
        }

        // auth headers
        if (!String.IsNullOrEmpty(this.ApplicationKey) && !String.IsNullOrEmpty(this.ApplicationSecret)) {
            headers.Add(new (System.Collections.Generic.KeyValuePair$2(String, String, 27758).ctor$1)($t.API_PARAM_KEY, 
                this.ApplicationKey));
            headers.Add(new (System.Collections.Generic.KeyValuePair$2(String, String, 27758).ctor$1)($t.API_PARAM_SIG, 
                this.get_SignatureGenerator().CreateSignature(this.ApplicationKey, this.ApplicationSecret)));
        }

        return sdkBridge.executeAsync(this.BaseUrl, request.GetResource(), $d.boxEnum(RestSharp.Method, 
            request.Method).toString().toUpperCase(), jsonBody, parameters, headers, request.ContentType);
    };
    $p.ConstructManualEndpoints = function StencilSDK_ConstructManualEndpoints() {
        this.Auth = new Stencil.SDK.Endpoints.AuthEndpoint.ctor(this);
    };
    $t.ctor$1 = function StencilSDK(baseUrl) {
        $t.ctor$4.call(this, String.Empty, String.Empty, baseUrl);
    };
    $t.ctor$3 = function StencilSDK(applicationKey, applicationSecret) {
        $t.ctor$4.call(this, applicationKey, applicationSecret, $t.API_BASE_URL);
    };
    $t.ctor = function StencilSDK(authInfo) {
        $t.ctor$4.call(this, authInfo.get_ApiKey(), authInfo.get_ApiSecret(), $t.API_BASE_URL);
    };
    $t.ctor$2 = function StencilSDK(authInfo, baseUrl) {
        $t.ctor$4.call(this, authInfo.get_ApiKey(), authInfo.get_ApiSecret(), baseUrl);
    };
    $t.ctor$4 = function StencilSDK(applicationKey, applicationSecret, baseUrl) {
        $t.$baseType.ctor.call(this);
        this.set_CustomHeaders(new (System.Collections.Generic.List$1(System.Collections.Generic.KeyValuePair$2(String, 
            String, 27758), 13064).ctor)());
        this.set_SignatureGenerator(new Stencil.SDK.Security.HashedTimeSignatureGenerator.ctor());

        this.AsyncTimeoutMillisecond = (System.TimeSpan.FromSeconds(40).get_TotalMilliseconds() | 0);
        this.ApplicationKey = applicationKey;
        this.ApplicationSecret = applicationSecret;
        if (baseUrl == null) {
            baseUrl = $t.API_BASE_URL;
        }
        this.BaseUrl = baseUrl;

        this.set_InstanceCache(new (System.Collections.Generic.Dictionary$2(String, System.Object, 58817).ctor)());

        this.ConstructCoreEndpoints();
        this.ConstructManualEndpoints();
    };
    $p.get_CustomHeaders = function StencilSDK_get_CustomHeaders() { return this.CustomHeaders; };
    $p.set_CustomHeaders = function StencilSDK_set_CustomHeaders(value) { this.CustomHeaders = value;return value; };
    $p.get_SignatureGenerator = function StencilSDK_get_SignatureGenerator() { return this.SignatureGenerator; };
    $p.set_SignatureGenerator = function StencilSDK_set_SignatureGenerator(value) { this.SignatureGenerator = value;return value; };
    $p.get_InstanceCache = function StencilSDK_get_InstanceCache() { return this.InstanceCache; };
    $p.set_InstanceCache = function StencilSDK_set_InstanceCache(value) { this.InstanceCache = value;return value; };
    $p.ConstructCoreEndpoints = function StencilSDK_ConstructCoreEndpoints() {
        this.GlobalSetting = new Stencil.SDK.Endpoints.GlobalSettingEndpoint.ctor(this);
        this.Account = new Stencil.SDK.Endpoints.AccountEndpoint.ctor(this);
        this.Asset = new Stencil.SDK.Endpoints.AssetEndpoint.ctor(this);

    };
});
$d.define(Stencil.WebAssumptions, null, function($t, $p) {
    $t.cctor = function() {
        $t.JS_BRIDGE_NAME = "StencilSDKBridge";
    };
});
$d.define(Stencil.SDK.ActionResult, null, function($t, $p) {
    $t.$ator = function() {
        this.success = false;
        this.message = null;
    };
    $t.ctor = function ActionResult() {
        $t.$baseType.ctor.call(this);
    };
    $p.get_success = function ActionResult_get_success() { return this.success; };
    $p.set_success = function ActionResult_set_success(value) { this.success = value;return value; };
    $p.get_message = function ActionResult_get_message() { return this.message; };
    $p.set_message = function ActionResult_set_message(value) { this.message = value;return value; };
});
$d.define(Stencil.SDK.Endpoints.EndpointBase, null, function($t, $p) {
    $t.$ator = function() {
        this.Sdk = null;
    };
    $t.ctor = function EndpointBase(sdk) {
        $t.$baseType.ctor.call(this);
        this.set_Sdk(sdk);
    };
    $p.get_Sdk = function EndpointBase_get_Sdk() { return this.Sdk; };
    $p.set_Sdk = function EndpointBase_set_Sdk(value) { this.Sdk = value;return value; };
});
$d.define(Stencil.SDK.Endpoints.AuthEndpoint, Stencil.SDK.Endpoints.EndpointBase, function($t, $p) {
    $t.ctor = function AuthEndpoint(api) {
        $t.$baseType.ctor.call(this, api);
    };
    $p.LoginAsync = function AuthEndpoint_LoginAsync(input) {
        var request = new RestSharp.RestRequest.ctor(1 /* Method.POST */);
        request.Resource = "auth/login";
        request.AddJsonBody(input);
        return this.get_Sdk().ExecuteAsync(Stencil.SDK.ItemResult$1(Stencil.SDK.Models.Responses.AccountInfo, 
            63703), request);
    };
    $p.RegisterAsync = function AuthEndpoint_RegisterAsync(input) {
        var request = new RestSharp.RestRequest.ctor(1 /* Method.POST */);
        request.Resource = "auth/register";
        request.AddJsonBody(input);
        return this.get_Sdk().ExecuteAsync(Stencil.SDK.ItemResult$1(Stencil.SDK.Models.Responses.AccountInfo, 
            63703), request);
    };
    $p.LogoutAsync = function AuthEndpoint_LogoutAsync() {
        var request = new RestSharp.RestRequest.ctor(1 /* Method.POST */);
        request.Resource = "auth/logout";
        return this.get_Sdk().ExecuteAsync(Stencil.SDK.ActionResult, request);
    };
    $p.PasswordResetStartAsync = function AuthEndpoint_PasswordResetStartAsync(email) {
        var input = (function() {
            var $obj = new Stencil.SDK.Models.Requests.PasswordResetInput.ctor();
            $obj.set_email(email);
            return $obj;
        }).call(this);
        var request = new RestSharp.RestRequest.ctor(1 /* Method.POST */);
        request.Resource = "auth/password_reset/start";
        request.AddJsonBody(input);
        return this.get_Sdk().ExecuteAsync(Stencil.SDK.ActionResult, request);
    };
    $p.PasswordResetCompleteAsync = function AuthEndpoint_PasswordResetCompleteAsync(email, token, password) {
        var input = (function() {
            var $obj = new Stencil.SDK.Models.Requests.PasswordResetInput.ctor();
            $obj.set_email(email);
            $obj.set_password(password);
            $obj.set_token(token);
            return $obj;
        }).call(this);
        var request = new RestSharp.RestRequest.ctor(1 /* Method.POST */);
        request.Resource = "auth/password_reset/complete";
        request.AddJsonBody(input);
        return this.get_Sdk().ExecuteAsync(Stencil.SDK.ActionResult, request);
    };
});
$d.define(Stencil.SDK.Endpoints.AccountEndpoint, Stencil.SDK.Endpoints.EndpointBase, function($t, $p) {
    $t.ctor = function AccountEndpoint(api) {
        $t.$baseType.ctor.call(this, api);
    };
    $p.GetAccountAsync = function AccountEndpoint_GetAccountAsync(account_id) {
        var request = new RestSharp.RestRequest.ctor(0 /* Method.GET */);
        request.Resource = "accounts/{account_id}";
        request.AddUrlSegment("account_id", account_id.toString());

        return this.get_Sdk().ExecuteAsync(Stencil.SDK.ItemResult$1(Stencil.SDK.Models.Account, 50101), 
            request);
    };
    $p.Find = function AccountEndpoint_Find(skip, take, keyword, order_by, descending) {
        var request = new RestSharp.RestRequest.ctor(0 /* Method.GET */);
        request.Resource = "accounts";
        request.AddParameter("skip", skip);
        request.AddParameter("take", take);
        request.AddParameter("order_by", order_by);
        request.AddParameter("descending", descending);
        request.AddParameter("keyword", keyword);


        return this.get_Sdk().ExecuteAsync(Stencil.SDK.ListResult$1(Stencil.SDK.Models.Account, 50101), 
            request);
    };
    $p.CreateAccountAsync = function AccountEndpoint_CreateAccountAsync(account) {
        var request = new RestSharp.RestRequest.ctor(1 /* Method.POST */);
        request.Resource = "accounts";
        request.AddJsonBody(account);
        return this.get_Sdk().ExecuteAsync(Stencil.SDK.ItemResult$1(Stencil.SDK.Models.Account, 50101), 
            request);
    };
    $p.UpdateAccountAsync = function AccountEndpoint_UpdateAccountAsync(account_id, account) {
        var request = new RestSharp.RestRequest.ctor(2 /* Method.PUT */);
        request.Resource = "accounts/{account_id}";
        request.AddUrlSegment("account_id", account_id.toString());
        request.AddJsonBody(account);
        return this.get_Sdk().ExecuteAsync(Stencil.SDK.ItemResult$1(Stencil.SDK.Models.Account, 50101), 
            request);
    };
    $p.DeleteAccountAsync = function AccountEndpoint_DeleteAccountAsync(account_id) {
        var request = new RestSharp.RestRequest.ctor(3 /* Method.DELETE */);
        request.Resource = "accounts/{account_id}";
        request.AddUrlSegment("account_id", account_id.toString());
        return this.get_Sdk().ExecuteAsync(Stencil.SDK.ActionResult, request);
    };
});
$d.define(Stencil.SDK.Endpoints.AssetEndpoint, Stencil.SDK.Endpoints.EndpointBase, function($t, $p) {
    $t.ctor = function AssetEndpoint(api) {
        $t.$baseType.ctor.call(this, api);
    };
    $p.GetAssetAsync = function AssetEndpoint_GetAssetAsync(asset_id) {
        var request = new RestSharp.RestRequest.ctor(0 /* Method.GET */);
        request.Resource = "assets/{asset_id}";
        request.AddUrlSegment("asset_id", asset_id.toString());

        return this.get_Sdk().ExecuteAsync(Stencil.SDK.ItemResult$1(Stencil.SDK.Models.Asset, 38769), 
            request);
    };
    $p.CreateAssetAsync = function AssetEndpoint_CreateAssetAsync(asset) {
        var request = new RestSharp.RestRequest.ctor(1 /* Method.POST */);
        request.Resource = "assets";
        request.AddJsonBody(asset);
        return this.get_Sdk().ExecuteAsync(Stencil.SDK.ItemResult$1(Stencil.SDK.Models.Asset, 38769), 
            request);
    };
    $p.UpdateAssetAsync = function AssetEndpoint_UpdateAssetAsync(asset_id, asset) {
        var request = new RestSharp.RestRequest.ctor(2 /* Method.PUT */);
        request.Resource = "assets/{asset_id}";
        request.AddUrlSegment("asset_id", asset_id.toString());
        request.AddJsonBody(asset);
        return this.get_Sdk().ExecuteAsync(Stencil.SDK.ItemResult$1(Stencil.SDK.Models.Asset, 38769), 
            request);
    };
    $p.DeleteAssetAsync = function AssetEndpoint_DeleteAssetAsync(asset_id) {
        var request = new RestSharp.RestRequest.ctor(3 /* Method.DELETE */);
        request.Resource = "assets/{asset_id}";
        request.AddUrlSegment("asset_id", asset_id.toString());
        return this.get_Sdk().ExecuteAsync(Stencil.SDK.ActionResult, request);
    };
});
$d.define(Stencil.SDK.Endpoints.GlobalSettingEndpoint, Stencil.SDK.Endpoints.EndpointBase, function($t, $p) {
    $t.ctor = function GlobalSettingEndpoint(api) {
        $t.$baseType.ctor.call(this, api);
    };
    $p.GetGlobalSettingAsync = function GlobalSettingEndpoint_GetGlobalSettingAsync(global_setting_id) {
        var request = new RestSharp.RestRequest.ctor(0 /* Method.GET */);
        request.Resource = "globalsettings/{global_setting_id}";
        request.AddUrlSegment("global_setting_id", global_setting_id.toString());

        return this.get_Sdk().ExecuteAsync(Stencil.SDK.ItemResult$1(Stencil.SDK.Models.GlobalSetting, 
            31911), request);
    };
    $p.Find = function GlobalSettingEndpoint_Find(skip, take, keyword, order_by, descending) {
        var request = new RestSharp.RestRequest.ctor(0 /* Method.GET */);
        request.Resource = "globalsettings";
        request.AddParameter("skip", skip);
        request.AddParameter("take", take);
        request.AddParameter("order_by", order_by);
        request.AddParameter("descending", descending);
        request.AddParameter("keyword", keyword);


        return this.get_Sdk().ExecuteAsync(Stencil.SDK.ListResult$1(Stencil.SDK.Models.GlobalSetting, 
            31911), request);
    };
    $p.CreateGlobalSettingAsync = function GlobalSettingEndpoint_CreateGlobalSettingAsync(globalsetting) {
        var request = new RestSharp.RestRequest.ctor(1 /* Method.POST */);
        request.Resource = "globalsettings";
        request.AddJsonBody(globalsetting);
        return this.get_Sdk().ExecuteAsync(Stencil.SDK.ItemResult$1(Stencil.SDK.Models.GlobalSetting, 
            31911), request);
    };
    $p.UpdateGlobalSettingAsync = function GlobalSettingEndpoint_UpdateGlobalSettingAsync(global_setting_id, globalsetting) {
        var request = new RestSharp.RestRequest.ctor(2 /* Method.PUT */);
        request.Resource = "globalsettings/{global_setting_id}";
        request.AddUrlSegment("global_setting_id", global_setting_id.toString());
        request.AddJsonBody(globalsetting);
        return this.get_Sdk().ExecuteAsync(Stencil.SDK.ItemResult$1(Stencil.SDK.Models.GlobalSetting, 
            31911), request);
    };
    $p.DeleteGlobalSettingAsync = function GlobalSettingEndpoint_DeleteGlobalSettingAsync(global_setting_id) {
        var request = new RestSharp.RestRequest.ctor(3 /* Method.DELETE */);
        request.Resource = "globalsettings/{global_setting_id}";
        request.AddUrlSegment("global_setting_id", global_setting_id.toString());
        return this.get_Sdk().ExecuteAsync(Stencil.SDK.ActionResult, request);
    };
});
$d.define(Stencil.SDK.IDPair, null, function($t, $p) {
    $t.$ator = function() {
        this.id = null;
        this.name = null;
        this.desc = null;
    };
    $t.ctor = function IDPair() {
        $t.$baseType.ctor.call(this);
    };
    $p.get_id = function IDPair_get_id() { return this.id; };
    $p.set_id = function IDPair_set_id(value) { this.id = value;return value; };
    $p.get_name = function IDPair_get_name() { return this.name; };
    $p.set_name = function IDPair_set_name(value) { this.name = value;return value; };
    $p.get_desc = function IDPair_get_desc() { return this.desc; };
    $p.set_desc = function IDPair_set_desc(value) { this.desc = value;return value; };
    $p.ToString = function IDPair_ToString() {
        return this.get_name();
    };
    $p.Equals = function IDPair_Equals(obj) {
        var other = $d.as(obj, Stencil.SDK.IDPair);
        if (other != null) {
            return this.get_id() == other.get_id();
        }
        return false;
    };
    $p.GetHashCode = function IDPair_GetHashCode() {
        return this.get_id().GetHashCode();
    };
});
$d.define(Stencil.SDK.ItemResult$1, Stencil.SDK.ActionResult, function($t, $p, T) {
    $t.$ator = function() {
        this.item = $d.defaultOf(T);
        this.meta = null;
    };
    $t.ctor = function ItemResult$1() {
        $t.$baseType.ctor.call(this);
    };
    $t.ctor$1 = function ItemResult$1(item, meta) {
        $t.$baseType.ctor.call(this);
        this.set_item(item);
        this.set_meta(meta);
    };
    $p.get_item = function ItemResult$1_get_item() { return this.item; };
    $p.set_item = function ItemResult$1_set_item(value) { this.item = value;return value; };
    $p.get_meta = function ItemResult$1_get_meta() { return this.meta; };
    $p.set_meta = function ItemResult$1_set_meta(value) { this.meta = value;return value; };
}, ["T"]);
$d.define(Stencil.SDK.ItemResult$2, Stencil.SDK.ActionResult, function($t, $p, TData, TMeta) {
    $t.$ator = function() {
        this.item = $d.defaultOf(TData);
        this.meta = $d.defaultOf(TMeta);
    };
    $t.ctor = function ItemResult$2() {
        $t.$baseType.ctor.call(this);
        this.set_meta($d.defaultOf(TMeta));
    };
    $t.ctor$1 = function ItemResult$2(item, meta) {
        $t.$baseType.ctor.call(this);
        this.set_item(item);
        this.set_meta(meta);
    };
    $p.get_item = function ItemResult$2_get_item() { return this.item; };
    $p.set_item = function ItemResult$2_set_item(value) { this.item = value;return value; };
    $p.get_meta = function ItemResult$2_get_meta() { return this.meta; };
    $p.set_meta = function ItemResult$2_set_meta(value) { this.meta = value;return value; };
}, ["TData", "TMeta"]);
$d.define(Stencil.SDK.ListResult$1, Stencil.SDK.ActionResult, function($t, $p, T) {
    $t.$ator = function() {
        this.items = null;
        this.paging = null;
        this.stepping = null;
    };
    $t.ctor = function ListResult$1() {
        $t.$baseType.ctor.call(this);
        this.set_items(new (System.Collections.Generic.List$1(T).ctor)());
    };
    $t.ctor$1 = function ListResult$1(items) {
        $t.$baseType.ctor.call(this);
        this.set_items(items);
    };
    $t.ctor$4 = function ListResult$1(items, paging) {
        $t.$baseType.ctor.call(this);
        this.set_items(items);
        this.set_paging(paging);
    };
    $t.ctor$5 = function ListResult$1(items, stepping) {
        $t.$baseType.ctor.call(this);
        this.set_items(items);
        this.set_stepping(stepping);
    };
    $t.ctor$2 = function ListResult$1(items, paging) {
        $t.$baseType.ctor.call(this);
        this.set_items(System.Linq.Enumerable.ToList(T, items));
        this.set_paging(paging);
    };
    $t.ctor$3 = function ListResult$1(items, stepping) {
        $t.$baseType.ctor.call(this);
        this.set_items(System.Linq.Enumerable.ToList(T, items));
        this.set_stepping(stepping);
    };
    $p.get_items = function ListResult$1_get_items() { return this.items; };
    $p.set_items = function ListResult$1_set_items(value) { this.items = value;return value; };
    $p.get_paging = function ListResult$1_get_paging() { return this.paging; };
    $p.set_paging = function ListResult$1_set_paging(value) { this.paging = value;return value; };
    $p.get_stepping = function ListResult$1_get_stepping() { return this.stepping; };
    $p.set_stepping = function ListResult$1_set_stepping(value) { this.stepping = value;return value; };
}, ["T"]);
$d.define(Stencil.SDK.ListResult$2, Stencil.SDK.ListResult$1, function($t, $p, TData, TMeta) {
    $t.$ator = function() {
        this.meta = $d.defaultOf(TMeta);
    };
    $t.ctor = function ListResult$2() {
        $t.$baseType.ctor.call(this);
        this.set_meta(new TMeta.ctor());
    };
    $p.get_meta = function ListResult$2_get_meta() { return this.meta; };
    $p.set_meta = function ListResult$2_set_meta(value) { this.meta = value;return value; };
}, ["TData", "TMeta"], [0]);
$d.define(Stencil.SDK.Models.SDKModel, null, function($t, $p) {
    $t.ctor = function SDKModel() {
        $t.$baseType.ctor.call(this);
    };
});
$d.define(Stencil.SDK.Models.Asset, Stencil.SDK.Models.SDKModel, function($t, $p) {
    $t.$ator = function() {
        this.asset_id = new System.Guid.ctor();
        this.type = 0 /* AssetType */;
        this.available = false;
        this.resize_required = false;
        this.encode_required = false;
        this.resize_processing = false;
        this.encode_processing = false;
        this.thumb_small_dimensions = null;
        this.thumb_medium_dimensions = null;
        this.thumb_large_dimensions = null;
        this.resize_status = null;
        this.resize_attempts = 0;
        this.resize_attempt_utc = undefined;
        this.encode_identifier = null;
        this.encode_status = null;
        this.raw_url = null;
        this.public_url = null;
        this.thumb_small_url = null;
        this.thumb_medium_url = null;
        this.thumb_large_url = null;
        this.encode_log = null;
        this.resize_log = null;
        this.dependencies = 0 /* Dependency */;
        this.encode_attempts = 0;
        this.encode_attempt_utc = undefined;
        this.resize_mode = null;
    };
    $t.ctor = function Asset() {
        $t.$baseType.ctor.call(this);
    };
    $p.get_asset_id = function Asset_get_asset_id() { return this.asset_id; };
    $p.set_asset_id = function Asset_set_asset_id(value) { this.asset_id = value;return value; };
    $p.get_type = function Asset_get_type() { return this.type; };
    $p.set_type = function Asset_set_type(value) { this.type = value;return value; };
    $p.get_available = function Asset_get_available() { return this.available; };
    $p.set_available = function Asset_set_available(value) { this.available = value;return value; };
    $p.get_resize_required = function Asset_get_resize_required() { return this.resize_required; };
    $p.set_resize_required = function Asset_set_resize_required(value) { this.resize_required = value;return value; };
    $p.get_encode_required = function Asset_get_encode_required() { return this.encode_required; };
    $p.set_encode_required = function Asset_set_encode_required(value) { this.encode_required = value;return value; };
    $p.get_resize_processing = function Asset_get_resize_processing() { return this.resize_processing; };
    $p.set_resize_processing = function Asset_set_resize_processing(value) { this.resize_processing = value;return value; };
    $p.get_encode_processing = function Asset_get_encode_processing() { return this.encode_processing; };
    $p.set_encode_processing = function Asset_set_encode_processing(value) { this.encode_processing = value;return value; };
    $p.get_thumb_small_dimensions = function Asset_get_thumb_small_dimensions() { return this.thumb_small_dimensions; };
    $p.set_thumb_small_dimensions = function Asset_set_thumb_small_dimensions(value) { this.thumb_small_dimensions = value;return value; };
    $p.get_thumb_medium_dimensions = function Asset_get_thumb_medium_dimensions() { return this.thumb_medium_dimensions; };
    $p.set_thumb_medium_dimensions = function Asset_set_thumb_medium_dimensions(value) { this.thumb_medium_dimensions = value;return value; };
    $p.get_thumb_large_dimensions = function Asset_get_thumb_large_dimensions() { return this.thumb_large_dimensions; };
    $p.set_thumb_large_dimensions = function Asset_set_thumb_large_dimensions(value) { this.thumb_large_dimensions = value;return value; };
    $p.get_resize_status = function Asset_get_resize_status() { return this.resize_status; };
    $p.set_resize_status = function Asset_set_resize_status(value) { this.resize_status = value;return value; };
    $p.get_resize_attempts = function Asset_get_resize_attempts() { return this.resize_attempts; };
    $p.set_resize_attempts = function Asset_set_resize_attempts(value) { this.resize_attempts = value;return value; };
    $p.get_resize_attempt_utc = function Asset_get_resize_attempt_utc() { return this.resize_attempt_utc; };
    $p.set_resize_attempt_utc = function Asset_set_resize_attempt_utc(value) { this.resize_attempt_utc = value;return value; };
    $p.get_encode_identifier = function Asset_get_encode_identifier() { return this.encode_identifier; };
    $p.set_encode_identifier = function Asset_set_encode_identifier(value) { this.encode_identifier = value;return value; };
    $p.get_encode_status = function Asset_get_encode_status() { return this.encode_status; };
    $p.set_encode_status = function Asset_set_encode_status(value) { this.encode_status = value;return value; };
    $p.get_raw_url = function Asset_get_raw_url() { return this.raw_url; };
    $p.set_raw_url = function Asset_set_raw_url(value) { this.raw_url = value;return value; };
    $p.get_public_url = function Asset_get_public_url() { return this.public_url; };
    $p.set_public_url = function Asset_set_public_url(value) { this.public_url = value;return value; };
    $p.get_thumb_small_url = function Asset_get_thumb_small_url() { return this.thumb_small_url; };
    $p.set_thumb_small_url = function Asset_set_thumb_small_url(value) { this.thumb_small_url = value;return value; };
    $p.get_thumb_medium_url = function Asset_get_thumb_medium_url() { return this.thumb_medium_url; };
    $p.set_thumb_medium_url = function Asset_set_thumb_medium_url(value) { this.thumb_medium_url = value;return value; };
    $p.get_thumb_large_url = function Asset_get_thumb_large_url() { return this.thumb_large_url; };
    $p.set_thumb_large_url = function Asset_set_thumb_large_url(value) { this.thumb_large_url = value;return value; };
    $p.get_encode_log = function Asset_get_encode_log() { return this.encode_log; };
    $p.set_encode_log = function Asset_set_encode_log(value) { this.encode_log = value;return value; };
    $p.get_resize_log = function Asset_get_resize_log() { return this.resize_log; };
    $p.set_resize_log = function Asset_set_resize_log(value) { this.resize_log = value;return value; };
    $p.get_dependencies = function Asset_get_dependencies() { return this.dependencies; };
    $p.set_dependencies = function Asset_set_dependencies(value) { this.dependencies = value;return value; };
    $p.get_encode_attempts = function Asset_get_encode_attempts() { return this.encode_attempts; };
    $p.set_encode_attempts = function Asset_set_encode_attempts(value) { this.encode_attempts = value;return value; };
    $p.get_encode_attempt_utc = function Asset_get_encode_attempt_utc() { return this.encode_attempt_utc; };
    $p.set_encode_attempt_utc = function Asset_set_encode_attempt_utc(value) { this.encode_attempt_utc = value;return value; };
    $p.get_resize_mode = function Asset_get_resize_mode() { return this.resize_mode; };
    $p.set_resize_mode = function Asset_set_resize_mode(value) { this.resize_mode = value;return value; };
});
Stencil.SDK.Models.AssetType = $d.typeEnum("Stencil.SDK.Models.AssetType", 45, $asm, 257, ["Image", "Video"], [0, 1]);
$d.define(Stencil.SDK.Models.Requests.AuthLoginInput, null, function($t, $p) {
    $t.$ator = function() {
        this.user = null;
        this.password = null;
        this.promotion = null;
        this.persist = false;
    };
    $t.ctor = function AuthLoginInput() {
        $t.$baseType.ctor.call(this);
    };
    $p.get_user = function AuthLoginInput_get_user() { return this.user; };
    $p.set_user = function AuthLoginInput_set_user(value) { this.user = value;return value; };
    $p.get_password = function AuthLoginInput_get_password() { return this.password; };
    $p.set_password = function AuthLoginInput_set_password(value) { this.password = value;return value; };
    $p.get_promotion = function AuthLoginInput_get_promotion() { return this.promotion; };
    $p.set_promotion = function AuthLoginInput_set_promotion(value) { this.promotion = value;return value; };
    $p.get_persist = function AuthLoginInput_get_persist() { return this.persist; };
    $p.set_persist = function AuthLoginInput_set_persist(value) { this.persist = value;return value; };
});
$d.define(Stencil.SDK.Models.Requests.PasswordResetInput, null, function($t, $p) {
    $t.$ator = function() {
        this.email = null;
        this.password = null;
        this.token = null;
    };
    $t.ctor = function PasswordResetInput() {
        $t.$baseType.ctor.call(this);
    };
    $p.get_email = function PasswordResetInput_get_email() { return this.email; };
    $p.set_email = function PasswordResetInput_set_email(value) { this.email = value;return value; };
    $p.get_password = function PasswordResetInput_get_password() { return this.password; };
    $p.set_password = function PasswordResetInput_set_password(value) { this.password = value;return value; };
    $p.get_token = function PasswordResetInput_get_token() { return this.token; };
    $p.set_token = function PasswordResetInput_set_token(value) { this.token = value;return value; };
});
$d.define(Stencil.SDK.Models.Requests.RegisterInput, null, function($t, $p) {
    $t.$ator = function() {
        this.email = null;
        this.first_name = null;
        this.last_name = null;
        this.password = null;
    };
    $t.ctor = function RegisterInput() {
        $t.$baseType.ctor.call(this);
    };
    $p.get_email = function RegisterInput_get_email() { return this.email; };
    $p.set_email = function RegisterInput_set_email(value) { this.email = value;return value; };
    $p.get_first_name = function RegisterInput_get_first_name() { return this.first_name; };
    $p.set_first_name = function RegisterInput_set_first_name(value) { this.first_name = value;return value; };
    $p.get_last_name = function RegisterInput_get_last_name() { return this.last_name; };
    $p.set_last_name = function RegisterInput_set_last_name(value) { this.last_name = value;return value; };
    $p.get_password = function RegisterInput_get_password() { return this.password; };
    $p.set_password = function RegisterInput_set_password(value) { this.password = value;return value; };
});
$d.define(Stencil.SDK.Models.Responses.AccountInfo, Stencil.SDK.Models.SDKModel, function($t, $p) {
    $t.$ator = function() {
        this.account_id = new System.Guid.ctor();
        this.email = null;
        this.first_name = null;
        this.last_name = null;
        this.api_key = null;
        this.api_secret = null;
        this.admin = false;
    };
    $t.ctor = function AccountInfo() {
        $t.$baseType.ctor.call(this);
    };
    $p.get_account_id = function AccountInfo_get_account_id() { return this.account_id; };
    $p.set_account_id = function AccountInfo_set_account_id(value) { this.account_id = value;return value; };
    $p.get_email = function AccountInfo_get_email() { return this.email; };
    $p.set_email = function AccountInfo_set_email(value) { this.email = value;return value; };
    $p.get_first_name = function AccountInfo_get_first_name() { return this.first_name; };
    $p.set_first_name = function AccountInfo_set_first_name(value) { this.first_name = value;return value; };
    $p.get_last_name = function AccountInfo_get_last_name() { return this.last_name; };
    $p.set_last_name = function AccountInfo_set_last_name(value) { this.last_name = value;return value; };
    $p.get_api_key = function AccountInfo_get_api_key() { return this.api_key; };
    $p.set_api_key = function AccountInfo_set_api_key(value) { this.api_key = value;return value; };
    $p.get_api_secret = function AccountInfo_get_api_secret() { return this.api_secret; };
    $p.set_api_secret = function AccountInfo_set_api_secret(value) { this.api_secret = value;return value; };
    $p.get_admin = function AccountInfo_get_admin() { return this.admin; };
    $p.set_admin = function AccountInfo_set_admin(value) { this.admin = value;return value; };
});
$d.define(Stencil.SDK.PagingInfo, null, function($t, $p) {
    $t.$ator = function() {
        this.total_items = 0;
        this.total_pages = 0;
        this.page_size = 0;
        this.current_page = 0;
    };
    $t.ctor = function PagingInfo() {
        $t.$baseType.ctor.call(this);
    };
    $t.ctor$1 = function PagingInfo(skip, take, total) {
        $t.$baseType.ctor.call(this);
        this.set_total_pages(0);
        this.set_current_page(1);

        this.set_total_items(total);
        this.set_page_size(take);

        if (total > 0 && take > 0) {
            this.set_total_pages((System.Math.Ceiling$1(total / take) | 0));
        }
        if ((skip + take) > take) {
            this.set_current_page((System.Math.Ceiling$1((skip + take) / take) | 0));
        }
    };
    $p.get_total_items = function PagingInfo_get_total_items() { return this.total_items; };
    $p.set_total_items = function PagingInfo_set_total_items(value) { this.total_items = value;return value; };
    $p.get_total_pages = function PagingInfo_get_total_pages() { return this.total_pages; };
    $p.set_total_pages = function PagingInfo_set_total_pages(value) { this.total_pages = value;return value; };
    $p.get_page_size = function PagingInfo_get_page_size() { return this.page_size; };
    $p.set_page_size = function PagingInfo_set_page_size(value) { this.page_size = value;return value; };
    $p.get_current_page = function PagingInfo_get_current_page() { return this.current_page; };
    $p.set_current_page = function PagingInfo_set_current_page(value) { this.current_page = value;return value; };
});
$d.define(Stencil.SDK.StencilAuthInfo, null, function($t, $p) {
    $t.$ator = function() {
        this.ApiKey = null;
        this.ApiSecret = null;
    };
    $t.ctor = function StencilAuthInfo() {
        $t.$baseType.ctor.call(this);
    };
    $p.get_ApiKey = function StencilAuthInfo_get_ApiKey() { return this.ApiKey; };
    $p.set_ApiKey = function StencilAuthInfo_set_ApiKey(value) { this.ApiKey = value;return value; };
    $p.get_ApiSecret = function StencilAuthInfo_get_ApiSecret() { return this.ApiSecret; };
    $p.set_ApiSecret = function StencilAuthInfo_set_ApiSecret(value) { this.ApiSecret = value;return value; };
});
$d.define(Stencil.SDK.Models.Account, Stencil.SDK.Models.SDKModel, function($t, $p) {
    $t.$ator = function() {
        this.account_id = new System.Guid.ctor();
        this.email = null;
        this.password = null;
        this.password_salt = null;
        this.disabled = false;
        this.api_key = null;
        this.api_secret = null;
        this.first_name = null;
        this.last_name = null;
        this.entitlements = null;
        this.password_reset_token = null;
        this.password_reset_utc = undefined;
        this.push_ios = null;
        this.push_google = null;
        this.push_microsoft = null;
        this.last_login_utc = undefined;
        this.last_login_platform = null;
    };
    $t.ctor = function Account() {
        $t.$baseType.ctor.call(this);
    };
    $p.get_account_id = function Account_get_account_id() { return this.account_id; };
    $p.set_account_id = function Account_set_account_id(value) { this.account_id = value;return value; };
    $p.get_email = function Account_get_email() { return this.email; };
    $p.set_email = function Account_set_email(value) { this.email = value;return value; };
    $p.get_password = function Account_get_password() { return this.password; };
    $p.set_password = function Account_set_password(value) { this.password = value;return value; };
    $p.get_password_salt = function Account_get_password_salt() { return this.password_salt; };
    $p.set_password_salt = function Account_set_password_salt(value) { this.password_salt = value;return value; };
    $p.get_disabled = function Account_get_disabled() { return this.disabled; };
    $p.set_disabled = function Account_set_disabled(value) { this.disabled = value;return value; };
    $p.get_api_key = function Account_get_api_key() { return this.api_key; };
    $p.set_api_key = function Account_set_api_key(value) { this.api_key = value;return value; };
    $p.get_api_secret = function Account_get_api_secret() { return this.api_secret; };
    $p.set_api_secret = function Account_set_api_secret(value) { this.api_secret = value;return value; };
    $p.get_first_name = function Account_get_first_name() { return this.first_name; };
    $p.set_first_name = function Account_set_first_name(value) { this.first_name = value;return value; };
    $p.get_last_name = function Account_get_last_name() { return this.last_name; };
    $p.set_last_name = function Account_set_last_name(value) { this.last_name = value;return value; };
    $p.get_entitlements = function Account_get_entitlements() { return this.entitlements; };
    $p.set_entitlements = function Account_set_entitlements(value) { this.entitlements = value;return value; };
    $p.get_password_reset_token = function Account_get_password_reset_token() { return this.password_reset_token; };
    $p.set_password_reset_token = function Account_set_password_reset_token(value) { this.password_reset_token = value;return value; };
    $p.get_password_reset_utc = function Account_get_password_reset_utc() { return this.password_reset_utc; };
    $p.set_password_reset_utc = function Account_set_password_reset_utc(value) { this.password_reset_utc = value;return value; };
    $p.get_push_ios = function Account_get_push_ios() { return this.push_ios; };
    $p.set_push_ios = function Account_set_push_ios(value) { this.push_ios = value;return value; };
    $p.get_push_google = function Account_get_push_google() { return this.push_google; };
    $p.set_push_google = function Account_set_push_google(value) { this.push_google = value;return value; };
    $p.get_push_microsoft = function Account_get_push_microsoft() { return this.push_microsoft; };
    $p.set_push_microsoft = function Account_set_push_microsoft(value) { this.push_microsoft = value;return value; };
    $p.get_last_login_utc = function Account_get_last_login_utc() { return this.last_login_utc; };
    $p.set_last_login_utc = function Account_set_last_login_utc(value) { this.last_login_utc = value;return value; };
    $p.get_last_login_platform = function Account_get_last_login_platform() { return this.last_login_platform; };
    $p.set_last_login_platform = function Account_set_last_login_platform(value) { this.last_login_platform = value;return value; };
});
Stencil.SDK.Models.Dependency = $d.typeEnum("Stencil.SDK.Models.Dependency", 45, $asm, 257, ["None"], [0]);
$d.define(Stencil.SDK.Models.GlobalSetting, Stencil.SDK.Models.SDKModel, function($t, $p) {
    $t.$ator = function() {
        this.global_setting_id = new System.Guid.ctor();
        this.name = null;
        this.value = null;
    };
    $t.ctor = function GlobalSetting() {
        $t.$baseType.ctor.call(this);
    };
    $p.get_global_setting_id = function GlobalSetting_get_global_setting_id() { return this.global_setting_id; };
    $p.set_global_setting_id = function GlobalSetting_set_global_setting_id(value) { this.global_setting_id = value;return value; };
    $p.get_name = function GlobalSetting_get_name() { return this.name; };
    $p.set_name = function GlobalSetting_set_name(value) { this.name = value;return value; };
    $p.get_value = function GlobalSetting_get_value() { return this.value; };
    $p.set_value = function GlobalSetting_set_value(value) { this.value = value;return value; };
});
$d.define(Stencil.SDK.SteppingInfo, null, function($t, $p) {
    $t.$ator = function() {
        this.more = false;
        this.skip = 0;
        this.current = 0;
        this.total = 0;
    };
    $t.ctor = function SteppingInfo() {
        $t.$baseType.ctor.call(this);
    };
    $p.get_more = function SteppingInfo_get_more() { return this.more; };
    $p.set_more = function SteppingInfo_set_more(value) { this.more = value;return value; };
    $p.get_skip = function SteppingInfo_get_skip() { return this.skip; };
    $p.set_skip = function SteppingInfo_set_skip(value) { this.skip = value;return value; };
    $p.get_current = function SteppingInfo_get_current() { return this.current; };
    $p.set_current = function SteppingInfo_set_current(value) { this.current = value;return value; };
    $p.get_total = function SteppingInfo_get_total() { return this.total; };
    $p.set_total = function SteppingInfo_set_total(value) { this.total = value;return value; };
});
$d.define(Stencil.SDK._ResultExtensions, null, function($t, $p) {
    $t.GetMessage = function _ResultExtensions_GetMessage(result, messageIfNull) {
        if (result != null && !String.IsNullOrEmpty(result.get_message())) {
            return result.get_message();
        }
        return messageIfNull;
    };
    $t.GetMessage$1 = function _ResultExtensions_GetMessage(ActionResult, result, messageIfNull) {
        if (result != null) {
            if (result.get_item() != null) {
                return Stencil.SDK._ResultExtensions.GetMessage$1(ActionResult, result, "Error Processing Request");
            }
            return result.get_message();
        }
        return messageIfNull;
    };
    $t.IsSuccess = function _ResultExtensions_IsSuccess(result) {
        if (result != null && result.get_success()) {
            return true;
        }
        return false;
    };
    $t.IsSuccess$1 = function _ResultExtensions_IsSuccess(T, result) {
        if (result != null && (result.get_success() || !System.Collections.Generic.EqualityComparer$1(T).get_Default().Equals$1(result.get_item(), 
            $d.defaultOf(T)))) {
            return true;
        }
        return false;
    };
    $t.IsSuccess$2 = function _ResultExtensions_IsSuccess(T, result) {
        if (result != null && (result.get_success() || result.get_items() != null)) {
            return true;
        }
        return false;
    };
    $t.IsSuccess$3 = function _ResultExtensions_IsSuccess(T, K, result) {
        if (result != null && result.get_success()) {
            return true;
        }
        return false;
    };
});
return $asm;
})();
//# sourceMappingURL=StencilSDKDuo.js.map
